### PR TITLE
Add http reason phrase

### PR DESCRIPTION
**Pull request by trevormorse**
Hey Guys,

This is a fix to add an http reason phrase to all responses from frapi. There is a bug in apache 2.2.x (I'm running 2.2.22) that causes any non standard HTTP Code without a reason phrase to be changed to a "500 Internal Server Error". See: https://issues.apache.org/bugzilla/show_bug.cgi?id=44995 and https://groups.google.com/forum/?fromgroups#!topic/frapi-general/yHGZYtLFWhw

I have added a http_phrase element to custom errors in frapi as well as a field in the admin interface and option in console for it. As well all other responses in frapi now include a reason phrase.

### CODE REVIEW

**Comment by dshafik** [comment]
@trevormorse I'd like to do a couple of things before we merge this:
1. Add a simple lookup array of standard codes => messages, so that if one is used and no http message is supplied, the default is used.
2. If it's a non-standard code, and no http message is supplied, re-use the error message

This should ensure minimal changes to existing users code, less friction for future users, and still give complete flexibility while avoiding the bug in every situation.

**Comment by trevormorse** [comment]
@dshafik in regards to 1, Apache already adds the appropriate reason phrases to standard http codes. So for instance:

``` php
throw new Frapi_Error('METHOD_NOT_ALLOWED', 'You can\'t call this method', 405);
```

will cause Apache to return a "405 Method Not Allowed". Do you know if nginx does/does not do this? I have no problem adding the mapping array if it's necessary, but want to make sure it is necessary :-)

**Comment by trevormorse** [comment]
@dshafik with that last commit I think I have both of your requests covered.

**Comment by trevormorse** [comment]
As discussed on IRC @dshafik I've added tests for the Error class including the reason phrase I have added as well as reason phrase tests to the response class tests.

**Comment by dshafik** [comment]
Did we decide to put this into 0.1.1 or 0.2.0? If the latter, can you close and re-issue the PR against the `dev` branch.

**Comment by trevormorse** [comment]
I think we said this was going in 0.1.1.

**Pull request merged**
