### PR TITLE
Add Travis Continuous Integration

### PR DESCRIPTION
**Pull request by dshafik**
This config adds a `.travis.yml` configuration, and a shell script for compiling `ext/apc` in the travis environment.

You can see see this in action on my fork, here: http://travis-ci.org/#!/dshafik/frapi

To enable it for the main frapi/frapi repo, an organization manager will need to follow the instructions here: http://about.travis-ci.org/docs/user/how-to-setup-and-trigger-the-hook-manually/

### CODE REVIEW

**Comment by helgi** [comment]
Do you want to add 5.2 into the travis YAML since that is our min supported PHP version? Or does Travis perhaps not support it?

**Comment by dshafik** [comment]
Given 5.2's EOL we should move this project to 5.3 IMO; regardless of Travis support.

**Comment by helgi** [comment]
FRAPI was originally 5.3 but due to most people that were using it, in the early days anyway, were stuck on 5.2 for whatever reason then we downgraded our support and changed code to facilitate.

An EOL doesn't equate to people not using it, unfortunantly (I can still see PHP 4 PEAR installer clients hit the PEAR download servers)

Would be curious to see what the FRAPI community thinks? Going to merge this one regardless but it is a good conversation to have since it could allow us to change the innards of FRAPI

**Comment by davidcoallier** [comment]
We are not going to force 5.3 just yet.

**Pull request merged**
