### PR TITLE
Updated getByKey() in src/frapi/library/Frapi/Action.php to return the default value (null) without casting it if empty or !isset()

### PR DESCRIPTION
**Pull request by Max13**
Previously, passing an empty non-required param to getParam(), returned the default value (null) casted as aksed to getParam(), so $value == NULL, would never happen.
Now, it will return the default value, without casting it.

When "$param == $default", I think it souldn't pass in the switch.

### CODE REVIEW

**Comment by dshafik** [comment]
@Max13 Can you reformat the change to include braces on the `if... else`? 

Have you confirmed the test suite still runs with this? If so, I'll merge after the change above.

**Comment by Max13** [comment]
@dshafik Unfortunately, I don't know why, but I've installed phpunit, and according to: https://github.com/frapi/frapi/wiki/Frapi-Unit-Tests, the command `phpunit` shows the help output.

I've tried: `phpunit -c phpunit.xml, couldn't read (the file has readable flag, and is in the current dir).
I've also tried:`php phpunit/phpunit.php`, shows the help output.

I'm on CentOS, either the phpunit package seems to be broken or I'm failing the cmds. :/
I'll add the braces anyway.

**Comment by davidcoallier** [comment]
Sorry to be picky about this but the braces should be inline with the `ifs` like such:

```
if (...) {
    // ...
} else {
    // ...
}
```

As soon as you change it I'll merge it I promise!

**Comment by Max13** [comment]
Moved to: Pull request #148 to avoid 3 commits.

**Pull request closed without merging**
